_raw_cfop = {
  'ENTRADA': {'1101': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 2415,
                                     'la_contabil': 10066},
                        'icms': {'c_icms': 2415,
                                 'd_icms': 224,
                                 'la_icms': 10067},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2415, 'd_ipi': 2541, 'la_ipi': 10068}},
             '1102': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1117': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1118': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1120': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 2415,
                                     'la_contabil': 10066},
                        'icms': {'c_icms': 2415,
                                 'd_icms': 224,
                                 'la_icms': 10067},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1121': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1126': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 4688,
                                     'la_contabil': 10113},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1128': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 4688,
                                     'la_contabil': 10113},
                        'icms': {'c_icms': 4688,
                                 'd_icms': 224,
                                 'la_icms': 10115},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1151.': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2695, 'd_ipi': 2541, 'la_ipi': 10128}},
             '1152': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1201': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10070},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 4429, 'd_ipi': 2541, 'la_ipi': 10071}},
             '1202': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10005},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10006},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1206': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 6100,
                                     'la_contabil': 10122},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10124},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1209': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10103},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10104},
                        'icms_st': {'c_icms_st': 126,
                                    'd_icms_st': 4681,
                                    'la_icms_st': 10121},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1251': {'contabil': {'c_contabil': 2933,
                                     'd_contabil': 1428,
                                     'la_contabil': 10041},
                        'icms': {'c_icms': 1428,
                                 'd_icms': 224,
                                 'la_icms': 80064},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1252': {'contabil': {'c_contabil': 2933,
                                     'd_contabil': 1428,
                                     'la_contabil': 10041},
                        'icms': {'c_icms': 1428,
                                 'd_icms': 224,
                                 'la_icms': 80064},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1303': {'contabil': {'c_contabil': 2940,
                                     'd_contabil': 1442,
                                     'la_contabil': 10042},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1352': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1353': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1401.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 2415,
                                     'la_contabil': 10066},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2415, 'd_ipi': 2541, 'la_ipi': 10068}},
             '1403.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1407.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1526,
                                     'la_contabil': 10043},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1409.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1410.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10070},
                        'icms_st': {'c_icms_st': 2919,
                                    'd_icms_st': 6100,
                                    'la_icms_st': 10078},
                        'ipi': {'c_ipi': 4429, 'd_ipi': 2541, 'la_ipi': 10071}},
             '1411.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10005},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10006},
                        'icms_st': {'c_icms_st': 2919,
                                    'd_icms_st': 6100,
                                    'la_icms_st': 10088},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1415.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1556.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1526,
                                     'la_contabil': 10043},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1557.0': {'contabil': {'c_contabil': 2995,
                                     'd_contabil': 1526,
                                     'la_contabil': 10126},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1652.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1653.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1568,
                                     'la_contabil': 10048},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1904.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1905.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 2835,
                                     'la_contabil': 10092},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 10096},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1906.0': {'contabil': {'c_contabil': 2835,
                                     'd_contabil': 273,
                                     'la_contabil': 10093},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10097},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1907.0': {'contabil': {'c_contabil': 2835,
                                     'd_contabil': 273,
                                     'la_contabil': 10093},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10097},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1908.0': {'contabil': {'c_contabil': 6105,
                                     'd_contabil': 280,
                                     'la_contabil': 80123},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1909.0': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 80100},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1910.0': {'contabil': {'c_contabil': 1995,
                                     'd_contabil': 273,
                                     'la_contabil': 10011},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10012},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1911.0': {'contabil': {'c_contabil': 1995,
                                     'd_contabil': 273,
                                     'la_contabil': 10011},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10012},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1912.0': {'contabil': {'c_contabil': 2884,
                                     'd_contabil': 2898,
                                     'la_contabil': 10028},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1916.0': {'contabil': {'c_contabil': 2723,
                                     'd_contabil': 2730,
                                     'la_contabil': 10014},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1917.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 4513,
                                     'la_contabil': 80060},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1918.0': {'contabil': {'c_contabil': 4499,
                                     'd_contabil': 273,
                                     'la_contabil': 80062},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1922.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1932.0': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1934.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 2835,
                                     'la_contabil': 10092},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 10096},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '1949.0': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10111},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2101.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 2415,
                                     'la_contabil': 10066},
                        'icms': {'c_icms': 2415,
                                 'd_icms': 224,
                                 'la_icms': 10067},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2415, 'd_ipi': 2541, 'la_ipi': 10068}},
             '2102.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2117.0': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2118.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2121.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2126.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 4688,
                                     'la_contabil': 10113},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2128.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 4688,
                                     'la_contabil': 10113},
                        'icms': {'c_icms': 4688,
                                 'd_icms': 224,
                                 'la_icms': 10115},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2151.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2695, 'd_ipi': 2541, 'la_ipi': 10128}},
             '2152.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2201.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10070},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 4429, 'd_ipi': 2541, 'la_ipi': 10071}},
             '2202.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10005},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10006},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2206.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 6100,
                                     'la_contabil': 10122},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10124},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2209.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10103},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10104},
                        'icms_st': {'c_icms_st': 126,
                                    'd_icms_st': 4681,
                                    'la_icms_st': 10121},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2251.0': {'contabil': {'c_contabil': 2933,
                                     'd_contabil': 1428,
                                     'la_contabil': 10041},
                        'icms': {'c_icms': 1428,
                                 'd_icms': 224,
                                 'la_icms': 80064},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2252.0': {'contabil': {'c_contabil': 2933,
                                     'd_contabil': 1428,
                                     'la_contabil': 10041},
                        'icms': {'c_icms': 1428,
                                 'd_icms': 224,
                                 'la_icms': 80064},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2303.0': {'contabil': {'c_contabil': 2940,
                                     'd_contabil': 1442,
                                     'la_contabil': 10042},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2352.0': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2353.0': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2401.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 2415,
                                     'la_contabil': 10066},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 2415, 'd_ipi': 2541, 'la_ipi': 10068}},
             '2403.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2407.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1526,
                                     'la_contabil': 10043},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2409.0': {'contabil': {'c_contabil': 2695,
                                     'd_contabil': 273,
                                     'la_contabil': 10003},
                        'icms': {'c_icms': 2695,
                                 'd_icms': 224,
                                 'la_icms': 10004},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2411.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10005},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10006},
                        'icms_st': {'c_icms_st': 2919,
                                    'd_icms_st': 6100,
                                    'la_icms_st': 10088},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2415.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2556.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1526,
                                     'la_contabil': 10043},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2557.0': {'contabil': {'c_contabil': 2995,
                                     'd_contabil': 1526,
                                     'la_contabil': 10126},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2652.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2653.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1568,
                                     'la_contabil': 10048},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2904.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2905.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 2835,
                                     'la_contabil': 10092},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 10096},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2906.0': {'contabil': {'c_contabil': 2835,
                                     'd_contabil': 273,
                                     'la_contabil': 10093},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10097},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2907.0': {'contabil': {'c_contabil': 2835,
                                     'd_contabil': 273,
                                     'la_contabil': 10093},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10097},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2908.0': {'contabil': {'c_contabil': 6105,
                                     'd_contabil': 280,
                                     'la_contabil': 80123},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2909.0': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 80100},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2910.0': {'contabil': {'c_contabil': 1995,
                                     'd_contabil': 273,
                                     'la_contabil': 10011},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10012},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2911.0': {'contabil': {'c_contabil': 1995,
                                     'd_contabil': 273,
                                     'la_contabil': 10011},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10012},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2912.0': {'contabil': {'c_contabil': 2884,
                                     'd_contabil': 2898,
                                     'la_contabil': 10028},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2916.0': {'contabil': {'c_contabil': 2723,
                                     'd_contabil': 2730,
                                     'la_contabil': 10014},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2917.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 4513,
                                     'la_contabil': 80060},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2918.0': {'contabil': {'c_contabil': 4499,
                                     'd_contabil': 273,
                                     'la_contabil': 80062},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2922.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2932.0': {'contabil': {'c_contabil': 2947,
                                     'd_contabil': 1708,
                                     'la_contabil': 10044},
                        'icms': {'c_icms': 1708,
                                 'd_icms': 224,
                                 'la_icms': 10045},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2934.0': {'contabil': {'c_contabil': 6183,
                                     'd_contabil': 2835,
                                     'la_contabil': 10092},
                        'icms': {'c_icms': 2856,
                                 'd_icms': 224,
                                 'la_icms': 10096},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '2949.0': {'contabil': {'c_contabil': '',
                                     'd_contabil': '',
                                     'la_contabil': ''},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10112},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '3102.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 273,
                                     'la_contabil': 10001},
                        'icms': {'c_icms': 273,
                                 'd_icms': 224,
                                 'la_icms': 10002},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '3128.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 4688,
                                     'la_contabil': 10113},
                        'icms': {'c_icms': 4688,
                                 'd_icms': 224,
                                 'la_icms': 10115},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             '3201.0': {'contabil': {'c_contabil': 126,
                                     'd_contabil': 1043,
                                     'la_contabil': 10069},
                        'icms': {'c_icms': 1057,
                                 'd_icms': 224,
                                 'la_icms': 10070},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': 4429, 'd_ipi': 2541, 'la_ipi': 10071}},
             '3653.0': {'contabil': {'c_contabil': 630,
                                     'd_contabil': 1568,
                                     'la_contabil': 10048},
                        'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                        'icms_st': {'c_icms_st': '',
                                    'd_icms_st': '',
                                    'la_icms_st': ''},
                        'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
             'nan': {'contabil': {'c_contabil': '',
                                  'd_contabil': '',
                                  'la_contabil': ''},
                     'icms': {'c_icms': '', 'd_icms': ',', 'la_icms': ''},
                     'icms_st': {'c_icms_st': '',
                                 'd_icms_st': '',
                                 'la_icms_st': ''},
                     'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}}},
 'SAIDA': {'5101': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '5102': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5104': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5117': {'contabil': {'c_contabil': '',
                                 'd_contabil': '',
                                 'la_contabil': ''},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '5120': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5124': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '5151': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10020},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2695, 'la_ipi': 10129}},
           '5152': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10020},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5201': {'contabil': {'c_contabil': 2415,
                                 'd_contabil': 630,
                                 'la_contabil': 10075},
                    'icms': {'c_icms': 658, 'd_icms': 2415, 'la_icms': 10076},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2415, 'la_ipi': 10077}},
           '5202': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 630,
                                 'la_contabil': 10021},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10022},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5209': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10105},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10106},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2695,
                                'la_icms_st': 10114},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5353': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5357': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5401': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10079},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '5402': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5403': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5405': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5409': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10020},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2695,
                                'la_icms_st': 10114},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5410': {'contabil': {'c_contabil': 2415,
                                 'd_contabil': 630,
                                 'la_contabil': 10075},
                    'icms': {'c_icms': 658, 'd_icms': 2415, 'la_icms': 10076},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2415, 'la_ipi': 10077}},
           '5411': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 630,
                                 'la_contabil': 10021},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10022},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10116},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5413': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 630,
                                 'la_contabil': 10053},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5415': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5556': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 630,
                                 'la_contabil': 10053},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5557': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 2695,
                                 'la_contabil': 10127},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5656': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5904': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5905': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2835,
                                 'la_contabil': 10094},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10098},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5906': {'contabil': {'c_contabil': 2835,
                                 'd_contabil': 6183,
                                 'la_contabil': 10099},
                    'icms': {'c_icms': 658, 'd_icms': 2856, 'la_icms': 10095},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5907': {'contabil': {'c_contabil': 2835,
                                 'd_contabil': 6183,
                                 'la_contabil': 10099},
                    'icms': {'c_icms': 658, 'd_icms': 2856, 'la_icms': 10095},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5910': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2961,
                                 'la_contabil': 10039},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10040},
                    'icms_st': {'c_icms_st': 686,
                                'd_icms_st': 1071,
                                'la_icms_st': 10117},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5912': {'contabil': {'c_contabil': 2877,
                                 'd_contabil': 2891,
                                 'la_contabil': 10026},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5913': {'contabil': {'c_contabil': 2898,
                                 'd_contabil': 2884,
                                 'la_contabil': 10029},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5916': {'contabil': {'c_contabil': 2905,
                                 'd_contabil': 2912,
                                 'la_contabil': 10036},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5917': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 4499,
                                 'la_contabil': 10090},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5918': {'contabil': {'c_contabil': 4513,
                                 'd_contabil': 6183,
                                 'la_contabil': 10091},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5922': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5927': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2191,
                                 'la_contabil': 10064},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10100},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10118},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5932': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5934': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2835,
                                 'la_contabil': 10094},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10098},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '5949': {'contabil': {'c_contabil': '',
                                 'd_contabil': '',
                                 'la_contabil': ''},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10112},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10119},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6101': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '6102': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6104': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6117': {'contabil': {'c_contabil': '',
                                 'd_contabil': '',
                                 'la_contabil': ''},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '6120': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6124': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '6151': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10020},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 666, 'd_ipi': 2696, 'la_ipi': 10130}},
           '6152': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10021},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6201': {'contabil': {'c_contabil': 2415,
                                 'd_contabil': 630,
                                 'la_contabil': 10075},
                    'icms': {'c_icms': 658, 'd_icms': 2415, 'la_icms': 10076},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2415, 'la_ipi': 10077}},
           '6202': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 630,
                                 'la_contabil': 10021},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10022},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6209': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10105},
                    'icms': {'c_icms': 659, 'd_icms': 2695, 'la_icms': 10106},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2695,
                                'la_icms_st': 10114},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6353': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6357': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6401': {'contabil': {'c_contabil': 1981,
                                 'd_contabil': 126,
                                 'la_contabil': 10072},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10073},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10079},
                    'ipi': {'c_ipi': 665, 'd_ipi': 4429, 'la_ipi': 10074}},
           '6402': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6403': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2919,
                                'la_icms_st': 10038},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6404': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6409': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2995,
                                 'la_contabil': 10019},
                    'icms': {'c_icms': 658, 'd_icms': 2695, 'la_icms': 10021},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 2695,
                                'la_icms_st': 10114},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6410': {'contabil': {'c_contabil': 2415,
                                 'd_contabil': 630,
                                 'la_contabil': 10075},
                    'icms': {'c_icms': 658, 'd_icms': 2415, 'la_icms': 10077},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2415, 'la_ipi': 10077}},
           '6411': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 630,
                                 'la_contabil': 10021},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10023},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10116},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6413': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 630,
                                 'la_contabil': 10053},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6415': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6556': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 630,
                                 'la_contabil': 10053},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6557': {'contabil': {'c_contabil': 1526,
                                 'd_contabil': 2695,
                                 'la_contabil': 10127},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6656': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6904': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6905': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2835,
                                 'la_contabil': 10094},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10098},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6906': {'contabil': {'c_contabil': 2835,
                                 'd_contabil': 6183,
                                 'la_contabil': 10099},
                    'icms': {'c_icms': 659, 'd_icms': 2856, 'la_icms': 10095},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6907': {'contabil': {'c_contabil': 2835,
                                 'd_contabil': 6183,
                                 'la_contabil': 10099},
                    'icms': {'c_icms': 659, 'd_icms': 2856, 'la_icms': 10095},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6910': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2961,
                                 'la_contabil': 10039},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10040},
                    'icms_st': {'c_icms_st': 686,
                                'd_icms_st': 1071,
                                'la_icms_st': 10117},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6912': {'contabil': {'c_contabil': 2877,
                                 'd_contabil': 2891,
                                 'la_contabil': 10026},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6913': {'contabil': {'c_contabil': 2898,
                                 'd_contabil': 2884,
                                 'la_contabil': 10029},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6916': {'contabil': {'c_contabil': 2905,
                                 'd_contabil': 2912,
                                 'la_contabil': 10036},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6917': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 4499,
                                 'la_contabil': 10090},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6918': {'contabil': {'c_contabil': 4513,
                                 'd_contabil': 6183,
                                 'la_contabil': 10091},
                    'icms': {'c_icms': '', 'd_icms': '', 'la_icms': ''},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6922': {'contabil': {'c_contabil': 1015,
                                 'd_contabil': 126,
                                 'la_contabil': 10015},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10016},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6932': {'contabil': {'c_contabil': 2611,
                                 'd_contabil': 126,
                                 'la_contabil': 10049},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10050},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6934': {'contabil': {'c_contabil': 273,
                                 'd_contabil': 2835,
                                 'la_contabil': 10094},
                    'icms': {'c_icms': 658, 'd_icms': 273, 'la_icms': 10098},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '6949': {'contabil': {'c_contabil': '',
                                 'd_contabil': '',
                                 'la_contabil': ''},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10112},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10119},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}},
           '7201': {'contabil': {'c_contabil': 2415,
                                 'd_contabil': 630,
                                 'la_contabil': 10075},
                    'icms': {'c_icms': 658, 'd_icms': 2415, 'la_icms': 10076},
                    'icms_st': {'c_icms_st': '',
                                'd_icms_st': '',
                                'la_icms_st': ''},
                    'ipi': {'c_ipi': 665, 'd_ipi': 2415, 'la_ipi': 10077}},
           '7949': {'contabil': {'c_contabil': '',
                                 'd_contabil': '',
                                 'la_contabil': ''},
                    'icms': {'c_icms': 658, 'd_icms': 1057, 'la_icms': 10112},
                    'icms_st': {'c_icms_st': 2926,
                                'd_icms_st': 273,
                                'la_icms_st': 10119},
                    'ipi': {'c_ipi': '', 'd_ipi': '', 'la_ipi': ''}}}
                    }
# Reorganiza para uso direto, removendo o sufixo ".0" dos CFOPs de entrada
CFOP_DATA = {
    'ENTRADA': {k.split('.')[0]: v for k, v in _raw_cfop['ENTRADA'].items()},
    'SAIDA':   _raw_cfop['SAIDA'].copy()
}